### ISSUE TITLE
Example of mergeIn not working

### ISSUE THREAD

**Issue by gcanti** [jlongster/tcomb-immutable-experiment#1]
From the readme

> There are holes in this. For example, `mergeIn` does not work with deep maps right now

is there an example somewhere of such a failing case?

**Comment by jlongster** [comment]
``` js
const Person = imstruct({
  name: t.union([t.String, t.Nil]),
  age: t.union([t.Number, t.Nil])
});

const People = imstruct({
  people: imdict(t.String, Person),
  areFun: t.Boolean
});

const people = People({
  people: { "James": { name: "James", age: 15 }},
  areFun: true
});

console.log(people.mergeIn(["people", "Jim"], { name: "Jim", age: 30 }));
```

The output of the above is:

```
Record { "people": Map {
  "James": Record { "name": "James", "age": 15 },
  "Jim": Record { "name": undefined, "age": undefined } },
"areFun": true }
```

Note how the name and age of Jim is undefined. If I change `Person` to not allow null, like this:

```
const Person = imstruct({
  name: t.String,
  age: t.Number
});
```

Then it errors with:

```
TypeError: [tcomb] Invalid value undefined supplied to ImDict {[key: String]: ImStruct{name: String, age: Number}}/Jim: ImStruct{name: String, age: Number}/name: String
```

The problem is here: https://github.com/facebook/immutable-js/blob/master/src/Map.js#L802

Immutable will automatically create Maps for you if they don't exist when traversing down a map with the `mergeIn` and other functions. Here, `Jim` does not exist so it created an `Immutable.Map` for you. I need _all_ maps in the typed structure to by my wrapped `TypedMap` object so it properly does the type checking/creation.

Now that I think about it, `setIn` and all the other `*In` functions have this problem too if any keys in the path create new maps for you.
